name: Run Postman Tests
on:
  push:
    branches: [main]
permissions:
  write-all
jobs:
  newman-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Newman and Allure Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-allure
      - name: Run Postman Collection with Allure Reporter
        run: |
          newman run Postman-Collection/Postman-Collection.json \
          --environment Restful.postman_environment.json \
          --reporters cli,allure \
          --reporter-allure-export allure-results
      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev
      - name: Load Allure Report History
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-history
      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
